### ISSUE TITLE
Improvement on clone function

### ISSUE THREAD

**Issue by EduardoAC** [radi-js/radi#10]
Currently, I was interested on looking the implementation of RadiJS and I saw an opportunity to contribute by pointing out an small enhancement.

Why do you create a helper if you use `Object.prototype.toString.call(obj) === "[object Array]"` on [line 25](https://github.com/radi-js/radi/blob/master/src/index.js#L25) instead of `isArray ` function that you use few lines above?

**Comment by rafaelklaessen** [comment]
Hi Eduardo, please check the refactor branch. It's already changed :)

**Comment by EduardoAC** [comment]
I didn't notice that the master was already under refactoring, thanks for pointing it out
