### ISSUE TITLE
Duplicated key in globals object.

### ISSUE THREAD

**Issue by Anderson-Vasques** [radi-js/radi#15]
Hey folks, first of all nice project :+1: 
I was hacking out the source code of refactoring branch and found a duplicated key in the GLOBALS object.
Is there any reason for that?
https://github.com/radi-https://github.com/radi-js/radi/blob/refactor/src/consts/GLOBALS.js#L11
https://github.com/radi-https://github.com/radi-js/radi/blob/refactor/src/consts/GLOBALS.js#L17

(Should I open issues related to refactoring branch here or should I discuss about int the slack channel?)

**Comment by rafaelklaessen** [comment]
I'm currently working on the refactor (see my fork) and I've removed it there.

**Comment by Anderson-Vasques** [comment]
Ok. I will close this issue then.
