### ISSUE TITLE
Would like to become a dev

### ISSUE THREAD

**Issue by goriunov** [radi-js/radi#2]
Hi, i have read your article in Medium, and i really like the idea which you are implementing. I would like to become one of the developers in the radi-js. I have thought about migrating the development source in to typescript and compile them to the browser implementation this way the project would be cleaner and better to maintain you can get some ideas from my repos https://github.com/ClusterWS/ClusterWS. If you are interested in this kinda approach just let me know. I would really like to help you in development of your library and may be whole ecosystem )

**Comment by rafaelklaessen** [comment]
Hi, maybe it's interesting for you to look at [this fork](https://github.com/colshacol/radi) and [my fork of that fork that adds tests](https://github.com/rafaelklaessen/radi) so that you can maybe work off that.

**Comment by Marcisbee** [comment]
Yes you can work with that, will see. You can join us on slack :) https://join.slack.com/t/radijs/shared_invite/enQtMjk3NTE2NjYxMTI2LWFmMTM5NTgwZDI5NmFlYzMzYmMxZjBhMGY0MGM2MzY5NmExY2Y0ODBjNDNmYjYxZWYxMjEyNjJhNjA5OTJjNzQ

Currently I'm cautious about code, but contributions are welcome :) Would love to work with you guys on this one

**Comment by NulledGravity** [comment]
Hey, I'd like to contribute too. I'll study the core of radi and then see if I can be of any help.

**Comment by Marcisbee** [comment]
@NulledGravity Hey, sure, join our slack ;) We're currently in code refactor stage tho (current active slack channel #refactor)
