### ISSUE TITLE
Feature Request: Custom Attributes

### ISSUE THREAD

**Issue by Rud156** [radi-js/radi#23]
> I don't think that this exists even in React as of now. But I found this feature really helpful in making custom functions for my application.

- The basic idea here is that we can pass in a custom attribute to the element that is linked to a global function or local function that defines functionality of the attribute

#### Example
- `<img src="Someting.jpg" />`. In case this fails you need to add a `onError` handler to manage the error state. Moreover these functions needs to be defined throughout the application and adding more functionality in such cases is difficult.
- So the custom attribute will do something like `<img source="Someting.jpg" />`. The `source` attribute is technically a function that takes the value and a reference to the element.
- Just custom functionality can be added more easily

#### In case I was unable to explain it properly Aurelia.JS has it and its pretty useful. https://aurelia.io/docs/templating/custom-attributes#introduction

**Comment by pichardoJ** [comment]
Similar to what attribute directives do in Angular, in React it can be solved with HOCs, which might also work with Radi. However I think it is cleaner the way Aurelia and Angular manage it

**Comment by Rud156** [comment]
Yes. I forgot about HOC when I created the issue. But the way Angular and Aurelia handle it is better

**Comment by rafaelklaessen** [comment]
I think that HOCs are already working with Radi since they aren't really React-specific.

**Comment by Marcisbee** [comment]
I actually really like this idea and see how useful it could be. We should come up with some idea (thinking about user facing API) how Radi could potentially do it.

I imagine something like this, it could be function or set of functions that takes element, value and perhaps component:

```jsx
customAttribute('source', (element, value) => {
   // Do something with element, listen to events etc
})

...

<img source="Something.jpg" />
```

```jsx
customAttribute('source', {
   default: (element, value) => {
      element.href = '/' + value
   },
   upper: (element, value) => {
      element.href = '/' + value.toUpperCase()
   },
})

...

<img source="Something.jpg" source.upper="Something.jpg" />
```

I currently cannot figure out how could we make those functions pure as they are mutating element anyways, so it might even be more intuitive to make them as classes. Thoughts ?

**Comment by Rud156** [comment]
In case of Aurelia it is implemented as a class.

**Comment by pichardoJ** [comment]
Thinking about this I think the only way to preserve immutability would be to decorate the element, having either the class or the function render to something like:

```javascript
class Source extends Radi.Attribute {

     constructor({value, upper}){}

    view(element){
        return <element href="{`/${this.upper ? this.upper.toUpperCase() :  this.value}" />
    }
}
```

or with function sintax 

```javascript 

customAttribute('source', element => <element href = "{`/${this.upper ? this.upper.toUpperCase() :  this.value}"/>);

// Or something semi-schematized like

customAttribute('source', {
    props: ['value', 'upper'],
    view: element => <element href = "{`/${this.upper ? this.upper.toUpperCase() :  this.value}`}"/>
});
```

**Comment by Marcisbee** [comment]
This feature is in the latest release.

The path I took was 

```js
Radi.customAttribute('relative-size', (element, value) => {
  element.style.fontSize = value + 'em';
  return `changed-${value * 100}`;
}, {
  allowedTags: ['li', 'ul'],  // Tags that can have this (default: null -> all tags)
  addToElement: true,         // Should add value/function to DOM node (default: true)
})
```

This example definition will work like this:

```jsx
<li relative-size={1.5}></li>
```

and output this (because addToElement was set):

```jsx
<li relative-size="changed-150"></li>
```

**Comment by rafaelklaessen** [comment]
Quite neat :smile:
