### ISSUE TITLE
Suggestion to improve the view parser

### ISSUE THREAD

**Issue by pygy** [radi-js/radi#4]
The way you parse the views currently is quite buggy, it can fail if comments or parens are present in strings.

A better strategy would be to use a single regex that matches strings, comments and the `/l\s*(/`, and ignore the strings/comment matches.

Something like this would do:

```JS
L_MATCHER = /((?:^|[^\w\d$])l\s*\()|"(?:\\.|[^"\n])*"|'(?:\\.|[^'\n])*'|\/\*[\s\S]*?\*\/|\/\/.*?\n/g

function findL(str, i) {
  var match;
  L_MATCHER.lastIndex = i;
  while (match = L_MATCHER.exec(str)) if(match[1] != null) {
    return match.index + match[1].length;
  }
}
```

You could also use a similar strategy to match parentheses.

`PAREN_MATCHER = /[()]|"(?:\\.|[^"\n])*"|'(?:\\.|[^'\n])*'|\/\*[\s\S]*?\*\/|\/\/.*?\n/g`
then ignore cases where `match[0]` is not a parenthesis.

**Comment by Marcisbee** [comment]
Thanks! Will look into this

**Comment by pygy** [comment]
Note that the above RegExps code doesn't take template literals into account. Parsing them properly is even more complex since you have to ballance `{`/`}` within interpolated expressions...

**Comment by lhorie** [comment]
I'm not sure this approach is worth pursuing further at all. The function call regex/replace will break non-local variable references. Here's a simple test case:

```js
const { r, l: x, mount, component } = radi;
 
const counter = component({
  view: function() {
    return (
      r('button', {onclick: this.up}, 'Click me ', x(this.counter))
    )
  },
  state: {
    counter: 0
  },
  actions: {
    up() {
      this.counter += 1;
    },
  }
});
 
mount(new counter(), document.body);

const input = document.getElementById('0');
```

So if `l` is renamed (which may happen, for example, if a bundler or a minifier renames it), things break.

Using any library will also break:

```js
const { r, l, mount, component } = radi;

function format(date) {return date.toString();}
 
const counter = component({
  view: function() {
    format(new Date());
    return (
      r('div', format(new Date))
    )
  },
  state: {
    counter: 0
  },
  actions: {
    up() {
      this.counter += 1;
    },
  }
});
 
mount(new counter(), document.body);

const input = document.getElementById('0');
```

**Comment by schtauffen** [comment]
I came here to report similar findings to lhorie above.

I do not feel the current approach is sustainable.

**Comment by Marcisbee** [comment]
Yes this approach is not great, but as a prototype it somewhat works for now.

I had plans of doing stuff like this in jsx (that would remove that clunky `l()` bind) or separate compiler (what could allow radi to modify js syntax as pleased) for radi, I just have not yet decided which approach to take.

**Comment by ambewas** [comment]
One argument against introducing odd/non-official js syntax with a separate compiler to put it all back together could be that every extra tool necessary for building something with radi other than the community standards like babel/webpack/npm/..., would hinder adoption efforts in the future.

If `l()` can be eliminated, all the better of course. Although I do like the explicit binding.

**Comment by Marcisbee** [comment]
@ambewas I agree. The purpose of that compiler would not be to replace js syntax, but to introduce better syntax for radi's clunky stuff only.

For example one wild idea for replacing `l()`: 

```jsx
...
<h1>
   My name is { this.person.name } {{ this.person.lastname }}
</h1>
...
```

`{ .. }` - could be static
`{{ .. }}` - could be dynamic, like `l()` is right now

This is just an idea, don't take this as a proposal tho. 😄 
Just wanted to explain what I mean by creating a "new syntax".

**Comment by schtauffen** [comment]
Would it not work to have `l` be a true export and trigger dynamic binding through calling it?
Currently the only reason to import `l` is to prevent `variable undefined` lint errors.

**Comment by rafaelklaessen** [comment]
I implemented a dynamic l function [here](https://github.com/rafaelklaessen/radi/tree/refactor-listener). It's far from done but it's dynamic.

**Comment by schtauffen** [comment]
With the current setup, I do not believe it is even possible to compose elements or accept props.

Am I missing something?

```
const Counter = component({
  view () { return <div><button />{ l("0") }<button/></div> }
})

const Main = component({
  view () { return <Counter /> }
})
// ERROR: Counter is undefined
```

**Comment by Marcisbee** [comment]
@schtauffen Lack of documentation currently makes testing of actual framework a bit hard, but it is possible.
Currently you need to register component globally with `register` function like so

```jsx
...

register( component({
   name: 'Counter',
   view () { return <div><button />{ l( this.count ) }<button/></div> },
   props: {
      count: 0   // Sets default value
   }
}) )

...

const Main = component({
  view () { return <Counter count={0} /> }
})
```

Altho I did not test this current code right now. But this is how it should work now.

**Comment by luwes** [comment]
Maybe check [Surplus](https://github.com/adamhaile/surplus) for inspiration, looks a bit similar concept wise but requires a compilation step... which Radi probably needs for removing that `new Function` (eval) stuff.
https://github.com/adamhaile/surplus

**Comment by Marcisbee** [comment]
With merging refactor into master, this is no longer relevant
